### ISSUE TITLE
Keypad not working

### ISSUE THREAD

**Issue by fmhwong** [chrisg20/KMK4cgM#1]
My keypad not longer lights up when plugged in.  According to README

```
To reinstall KMK from the beginning, first put the macropad into editor mode by holding down the center key and plugging it into your computer.

A CGM-33 drive will show up like a USB flash drive in your file explorer. Find it and delete all its contents.

Next, download the base KMK firmware according to steps 1-3 of the guide [here](https://github.com/KMKfw/kmk_firmware/blob/master/docs/en/Getting_Started.md).

Then, copy ONLY the KMK folder and the boot.py file from this page onto the USB drive (appearing as CGM-33).
```

Questions:

1. From `https://learn.adafruit.com/welcome-to-circuitpython/installing-circuitpython`, there are firmware for 410 boards.  Which one should I use?
2. There is no boot.py on this page.  Where should I get it?

**Comment by chrisg20** [comment]
Hello!

There should be no need to reinstall circuitpython. The missing boot file is now in the CGM-33 folder, you should now be able to reset the board by deleting everything from it and then copying to it everything here: https://github.com/chrisg20/KMK4cgM/tree/main/CGM-33

Let me know if this works!

**Comment by fmhwong** [comment]
That helps!  Thank you!
